# Generated by Django 2.2.2 on 2019-11-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formpesanan', '0003_auto_20191126_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='alamat',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='catatan',
            field=models.CharField(default='', max_length=20),
        ),
    ]
