# Generated by Django 2.2.2 on 2019-11-23 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPesananPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('no_wa', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nama_barang', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Pesanan',
                'verbose_name_plural': 'Pesanans',
            },
            bases=('wagtailcore.page',),
        ),
    ]
